### PR TITLE
Bug fix for AppInfoForm and updated error message for invalid apiBasePath when using Netlify functions

### LINKED ISSUE #263: AppInfoForm bug: apiDomain and websiteDomain do not ignore case for Localhost
## Problem
- For the `apiDomain` and `websiteDomain` fields inside `AppInfoForm`, if we insert values non-lowercase values of "localhost" ( like `Localhost`, `LOCALHOST`, etc ), it gives an 'Invalid domain' error.
- As it considers non-lowercase `localhost` values invalid, if we use `Localhost` with different ports for `apiDomain` and `websiteDomain`, it results to `""`. This as a result, gives a false error that `apiBasePath` cannot be equal to, be a prefix of or be a prefix to `websiteBasePath`.

## Solution
- Convert the domains to lower case before normalising the domain. As we use JS' `URL` object in the domain normalization process, the output domain is already in lower case, so converting the input to lowercase too doesn't change the original output.

### PR DESCRIPTION
**Pull request by st-jay**
## Related issues
- #263 
- #254 

## Summary of changes
- fixed #263 - Convert the domain to lower case using `String.toLowerCase()` method when calling the normalization class `NormalisedURLDomain`.
- #254: Updated the error message we show when using Netlify Functions and the apiBasePath is not prefixed by `/.netlify/functions/` or does not contain any path after that.
  - Updated message: **"apiBasePath must be prefixed with \`/.netlify/functions\`, for example to use \`/auth\` set the apiBasePath to \`/.netlify/functions/auth\`"**

## Checklist
- [ ] ~Algolia search needs to be updated? (If there is a new sub docs project, then yes)~
- [ ] ~Sitemap needs to be updated? (If there is a new sub docs project, then yes)~
- [ ] ~Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)~
- [ ] ~Changes required to the demo apps corresponding to the docs?~

## Remaining TODOs for this PR
No todos remaining

### CODE REVIEW

File: v2/src/components/appInfoForm/index.tsx [hunk 1]
```diff
@@ -667,11 +671,7 @@ export default class AppInfoForm extends React.PureComponent<PropsWithChildren<P
                     ) {
                         // if the netlify api route checkbox is set to true
                         // the api base path can only start with `/.netlify/functions`
-                        validationErrors.apiBasePath = "apiBasePath should begin with '/.netlify/functions/' when using Netlify Serverless Functions."
-                    } else if (netlifyApiRouteUsed && validApiBasePath === "/.netlify/functions/") {
```
Comment (st-jay) [inline v2/src/components/appInfoForm/index.tsx:671]: @nkshah2 I've removed this condition as the `validApiBasePath` will never be equal to `/.netlify/functions/` as the path normalization function we use removes the trailing `/`

**Review by nkshah2 — APPROVED** [review]
